### ISSUE TITLE
Start A Game Scene Terrain Pink Color Error

### ISSUE THREAD

**Issue by PjLovePb** [MinaPecheux/UnityTutorials-RTS#6]
![image](https://user-images.githubusercontent.com/40516128/166888292-8e3bb633-11c1-4161-967f-91352fd4c834.png)

**Comment by MinaPecheux** [comment]
Hello! Given that there isn't more info, I can suggest that this error comes either from:
- an unexistent terrain texture (ie the terrain is assigned a texture that doesn't exist anymore)
- or a pipeline issue that causes some shading/rendering problems: this can happen in particular if you use other Unity versions and had to "upgrade"/"downgrade" the project... take a look at the bottom of the README in this repo for more details

I hope it helps,
else feel free to drop in more data on your issue!
Cheers.
