### ISSUE TITLE
abe aale sab kuch purple ara pl help

### ISSUE THREAD

**Issue by Feartheyc** [MinaPecheux/UnityTutorials-RTS#7]
Everything is purple after importing help

**Comment by MinaPecheux** [comment]
Hi @Feartheyc !
My guess is that you're probably using a different Unity editor version than the one used in this demo (Unity 2020.3) and the materials are therefore incompatible... to solve the issue, the easiest solution would be to install another version of the Unity version on your computer (using the Unity Hub, go to the "Installs" section in the sidebar) that is compatible with this project. A Unity 2020.3+ version should do :)

Hope it helps,
cheers!

**Comment by Feartheyc** [comment]
OK. Thanks for the reply. Will try on the Unity 2020.3 versions

**Comment by MinaPecheux** [comment]
Closing this issue since it looks like a specific setup/config thing :)
